# Base configs
baseurl: "https://photography.rampatra.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Lee"
subtitle: "Anytime in my life"
author: "Yuanzhe Li(Lee)"
header:
 title: "Lee's World"
 subtitle: "by Yuanzhe Li"
footer:
 name: "Hey there, my name is Lee"
 bio: "Lee from China, with Photography in Anytime."

web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/liyuanzhe555"
